### PR TITLE
Closes #16 Upgrade to latest versions of dependencies

### LINKED ISSUE #16: Upgrade to latest versions of dependencies
Upgrading all `narwin-pack` dependencies to latest versions.

### PR DESCRIPTION
**Pull request by danrichman**
Closes #16 Upgrade to latest versions of dependencies

### CODE REVIEW

**Review by cory-tanner — APPROVED** [review]

**Comment by danrichman** [comment]
Test @DockYard/uxd

**Comment by danrichman** [comment]
Test @DockYard/uxd 
Please ignore.

**Review by danrichman — COMMENTED** [review]
@DockYard/uxd Test. Please ignore.

**Review by danrichman — COMMENTED** [review]
Test @danrichman. Please ignore.

**Review by danrichman — COMMENTED** [review]
Testing @danrichman Please ignore.

**Review by danrichman — COMMENTED** [review]
Testing @danrichman Please ignore

**Pull request merged**
